[technote]
id = "SITCOMTN-138"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-138.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-138"
github_default_branch = "main"
date_created = 2024-09-12T22:55:10Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Bruno C."
name.family = "Quint"
internal_id = "quintb"
orcid = "https://orcid.org/0000-0002-1557-3560"
[[technote.authors.affiliations]]
name = "Vera C. Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ 85719, USA"
